(function(){
const app=document.getElementById('app');const nav=document.getElementById('prophetNav');let activeTab='story';
const preview={adam:['🌿','☁️','💧'],idris:['🧵','🪡','〰'],nuh:['⛵','🌧️','🌊'],hud:['🏛️','🌾','💨'],salih:['⛰️','🐪','☀️'],lut:['🏠','✦','🌙'],ibrahim:['🔥','✦','🔥'],ismail:['🕋','☀️','💧'],ishaq:['⛺','🌿','☀️'],yaqub:['📖','🪔','🪟'],yusuf:['🪣','🕳️','☀️'],shuayb:['🐪','📦','〰'],ayyub:['🪟','🌱','☀️'],dhulkifl:['⚖️','🏛️','✦'],musa:['△','☀️','〰'],harun:['✦','◼','☀️'],dawud:['🛡️','⚔️','✦'],sulayman:['🏛️','🐦','⛲'],ilyas:['⛰️','⚡','☁️'],alyasa:['🌿','💧','⛰️'],yunus:['🐋','●','💧'],zakariya:['🌳','🍃','☀️'],yahya:['☾','✦','✧'],isa:['🌿','💧','☀️'],muhammad:['🌹','🌿','🌸']};
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function refParts(ref){const [s,a]=ref.split(':');return{surah:Number(s),ayah:a}}
function expandRef(ref){const {surah,ayah}=refParts(ref);if(!ayah.includes('-'))return[`${surah}:${ayah}`];const [a,b]=ayah.split('-').map(Number);return Array.from({length:b-a+1},(_,i)=>`${surah}:${a+i}`)}
function arabicFor(ref){return expandRef(ref).map(k=>window.quranArabic[k]||'').filter(Boolean).join(' ۝ ')}
function quranUrl(ref){const {surah,ayah}=refParts(ref);return`https://quran.com/${surah}/${ayah.split('-')[0]}`}
function refLabel(ref){const {surah}=refParts(ref);return`${window.surahNames[surah]||(t('surah')+' '+surah)} ${ref}`}
function renderNav(){nav.innerHTML=window.prophetsData.map(p=>`<button class="nav-item ${location.hash==='#'+p.id?'active':''}" data-prophet-link="${p.id}"><span class="nav-num">${String(p.number).padStart(2,'0')}</span><span>${esc(p.name[currentLang])}</span></button>`).join('')}
function ayahMeaningFor(ref,fallback=''){const item=window.quranMeaning?.[ref];return item?.[currentLang]||fallback||t('ayahMeaningGeneric')}
function ayahBlock(ref,title,meaning='',open=false){const translated=ayahMeaningFor(ref,meaning);return `<section class="ayah-block ${open?'open':''}"><button class="ayah-toggle" data-ayah-toggle><span><strong>${esc(title)}</strong><span class="ayah-ref">${esc(refLabel(ref))}</span></span><span>⌄</span></button><div class="ayah-content"><div class="ayah-arabic" lang="ar">${arabicFor(ref)}</div><div class="ayah-meaning"><strong>${t('meaning')}:</strong><p>${esc(translated)}</p><small>${esc(t('translationNote'))}</small></div><div class="ayah-actions"><a class="ghost-btn" href="${quranUrl(ref)}" target="_blank" rel="noopener">${t('quranLink')} ↗</a></div></div></section>`}
function card(p){const icons=preview[p.id]||['✦','☾','❋'];return `<article class="prophet-card" data-prophet-link="${p.id}" tabindex="0"><div class="card-preview" aria-hidden="true">${icons.map(x=>`<span>${x}</span>`).join('')}</div><span class="card-num">${String(p.number).padStart(2,'0')}</span><h3>${esc(p.name[currentLang])}</h3><div class="card-ar">${p.name.ar}</div><p>${esc(p.description[currentLang])}</p></article>`}
function renderHome(){activeTab='story';document.body.removeAttribute('data-prophet');loadProphetScene(null);renderNav();app.innerHTML=`<div class="content-wrap"><section class="hero"><div class="hero-copy"><div class="hero-kicker">${t('tagline')}</div><h1>${t('title')}</h1><p>${t('heroText')}</p><div class="hero-actions"><button class="primary-btn" data-prophet-link="adam">${t('start')} →</button><a class="ghost-btn" href="#prophetsGrid">25 ${t('prophetsCount').replace('25 ','')}</a></div></div></section><section class="home-section" id="prophetsGrid"><h2>${t('chooseStory')}</h2><div class="search-box"><input id="prophetSearch" placeholder="${esc(t('search'))}" autocomplete="off"></div><div id="cardsGrid" class="cards-grid">${window.prophetsData.map(card).join('')}</div></section></div>`;const input=document.getElementById('prophetSearch');input.addEventListener('input',()=>{const q=input.value.trim().toLocaleLowerCase(currentLang==='kk'?'kk-KZ':'ru-RU');document.getElementById('cardsGrid').innerHTML=window.prophetsData.filter(p=>(p.name[currentLang]+' '+p.name.ar+' '+p.description[currentLang]).toLocaleLowerCase().includes(q)).map(card).join('')})}
function renderStory(p){const chapters=p.chapters[currentLang];let out='';chapters.forEach((c,i)=>{out+=`<section class="story-chapter"><h2>${esc(c.title)}</h2><p>${esc(c.text)}</p></section>`;if(p.keyAyahs[i])out+=ayahBlock(p.keyAyahs[i],c.title,'',i===0)});out+=`<section class="all-ayahs"><h2>${t('allAyahs')}</h2><div class="ayah-index">${p.allAyahs.map((r,i)=>`<button data-scroll-ayah="all-${p.id}-${i}"><span class="ayah-ref">${String(i+1).padStart(2,'0')}</span> — ${esc(refLabel(r))}</button>`).join('')}</div><div style="margin-top:16px">${p.allAyahs.map((r,i)=>`<div id="all-${p.id}-${i}">${ayahBlock(r,refLabel(r),'')}</div>`).join('')}</div></section>`;return out}
function renderDua(p){if(!p.dua)return`<div class="empty-note">${t('noDua')}</div>`;return `<article class="dua-card"><div class="source-row"><span class="badge gold">Құран ${p.dua.ref}</span></div><div class="dua-arabic">${p.dua.arabic}</div><p>${esc(p.dua[currentLang])}</p><a class="ghost-btn" target="_blank" rel="noopener" href="${quranUrl(p.dua.ref)}">${t('quranLink')} ↗</a></article>`}
function renderHadith(p){const h=p.hadith;return `<article class="hadith-card"><div class="source-row"><span class="badge">${esc(h.collection)}</span><span class="badge gold">${h.number==='—'?'—':'№ '+esc(h.number)}</span><span>${t('grade')}: ${esc(h.grade)}</span></div><p>${esc(h[currentLang])}</p>${h.url?`<a class="ghost-btn" href="${h.url}" target="_blank" rel="noopener">${t('source')} ↗</a>`:''}</article>`}
function renderFacts(p){const surahs=p.facts.relatedSurahs.map(s=>window.surahNames[s]||s).join(' · ');let reliability=t('reliabilityText');return `<div class="fact-grid"><article class="fact-card"><span class="badge">${t('fact')}</span><div class="fact-value">${p.facts.mentionCount}</div><p>${t('mentioned')} — ${p.facts.mentionCount} ${t('times')}.</p></article><article class="fact-card"><span class="badge gold">${t('relatedSurahs')}</span><p>${esc(surahs)}</p></article></div><article class="fact-card"><h3>${t('directMentions')}</h3><p class="ref-chips">${p.facts.mentionRefs.map(r=>`<button class="ref-chip" data-open-ref="${r}">${esc(r)}</button>`).join('')}</p><p class="source-row">${t('mentionLinksNote')}</p></article><article class="fact-card"><span class="badge gold">${t('reliability')}</span><p>${esc(reliability)}</p></article>`}
function bodyFor(p){if(activeTab==='dua')return renderDua(p);if(activeTab==='hadith')return renderHadith(p);if(activeTab==='facts')return renderFacts(p);return renderStory(p)}
function renderProphet(id){const p=window.prophetsData.find(x=>x.id===id);if(!p){renderHome();return}document.body.classList.remove('menu-open');loadProphetScene(id);renderNav();const i=window.prophetsData.indexOf(p),prev=window.prophetsData[i-1],next=window.prophetsData[i+1];app.innerHTML=`<article class="article-shell"><header class="article-head"><div class="article-num">${String(p.number).padStart(2,'0')} / 25</div><div class="article-ar">${p.name.ar}</div><h1>${esc(p.name[currentLang])}</h1><p class="article-desc">${esc(p.description[currentLang])}</p></header><nav class="tabs" aria-label="Tabs"><button class="tab-button ${activeTab==='story'?'active':''}" data-tab="story">${t('story')}</button><button class="tab-button ${activeTab==='dua'?'active':''}" data-tab="dua">${t('dua')}</button><button class="tab-button ${activeTab==='hadith'?'active':''}" data-tab="hadith">${t('hadith')}</button><button class="tab-button ${activeTab==='facts'?'active':''}" data-tab="facts">${t('facts')}</button></nav><div id="tabBody">${bodyFor(p)}</div><nav class="article-footer-nav">${prev?`<button data-prophet-link="${prev.id}">← ${t('prev')}<br><strong>${esc(prev.name[currentLang])}</strong></button>`:'<span></span>'}${next?`<button data-prophet-link="${next.id}">${t('next')} →<br><strong>${esc(next.name[currentLang])}</strong></button>`:'<span></span>'}</nav></article>`;app.focus({preventScroll:true})}
function rerenderCurrent(){const id=location.hash.slice(1);if(id&&window.prophetsData.some(p=>p.id===id))renderProphet(id);else renderHome()}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab){activeTab=tab.dataset.tab;const id=location.hash.slice(1);renderProphet(id);return}const tog=e.target.closest('[data-ayah-toggle]');if(tog){tog.closest('.ayah-block').classList.toggle('open');return}const s=e.target.closest('[data-scroll-ayah]');if(s){const el=document.getElementById(s.dataset.scrollAyah);el?.scrollIntoView({behavior:'smooth',block:'start'});setTimeout(()=>el?.querySelector('.ayah-block')?.classList.add('open'),280)}const r=e.target.closest('[data-open-ref]');if(r){window.open(quranUrl(r.dataset.openRef),'_blank','noopener')}});
document.addEventListener('keydown',e=>{const c=e.target.closest?.('.prophet-card');if(c&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openProphet(c.dataset.prophetLink)}});
window.addEventListener('hashchange',()=>{activeTab='story';rerenderCurrent();scrollTo({top:0,behavior:'smooth'})});window.addEventListener('languagechange',rerenderCurrent);
window.addEventListener('scroll',()=>{const d=document.documentElement,max=d.scrollHeight-innerHeight;document.documentElement.style.setProperty('--reading',max>0?`${Math.min(100,scrollY/max*100)}%`:'0%')},{passive:true});
applyLanguage(currentLang);rerenderCurrent();
})();
